#!/bin/sh
#
# Copyright (c) 2011, The University of York
# All rights reserved.
# Author(s):
#   Tai Chi Minh Ralph Eastwood <tcmreastwood@gmail.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the The University of York nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# ANY ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE UNIVERSITY OF YORK BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

DIR=`cd -P "\`dirname \"$0\"\`" && pwd`

# Detect python installation
PYTHON=`which python 2>/dev/null`
if [ -f "$PYTHON" ]
then
	VERSION=`$PYTHON --version 2>&1 | cut -d' ' -f2 | cut -b 1`
	PYVERSION=`$PYTHON --version 2>&1 | cut -d' ' -f2 | cut -b 1-3`
else
	echo "Default python installation does not seem to be present!"
	exit 1
fi

if [ ! "x$VERSION" = "x2" ]
then
	echo "Default python installation is version $VERSION, trying python2 binary."
	PYTHON=`which python2 2>/dev/null`
	if [ -f "$PYTHON" ]
	then
		VERSION=`$PYTHON --version 2>&1 | cut -d' ' -f2 | cut -b 1`
		PYVERSION=`$PYTHON --version 2>&1 | cut -d' ' -f2 | cut -b 1-3`
	else
		echo "Cannot find python2 installation!"
		exit 1
	fi
	if [ "x$VERSION" = "x2" ]
	then
		echo "Found Python 2 installation."
	else
		echo "Python installation is version $VERSION, not version 2."
		exit 1
	fi
fi

if [ -f "$DIR/src/playernsd/__main__.py" ]
then
	#export PYTHONPATH=src
	export PYTHONPATH=$DIR/src
	exec $PYTHON $DIR/src/playernsd $*
else
	exec $PYTHON $DIR/playernsd $*
fi
